### ISSUE TITLE
[Bug] Update `run-integration-tests-hatch` part of `internal-archive-release.yml` to test against current branch

### ISSUE THREAD

**Issue by McKnight-42** [dbt-labs/dbt-release#121]
### Is this a new bug in dbt-release?

- [X] I believe this is a new bug in dbt-release
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

```
run-integration-tests-hatch:
    name: 'Integration Tests (Hatch)'
    needs: [initial-setup, job-setup, run-unit-tests-hatch]
    if: |
      needs.initial-setup.outputs.is_hatch_adapter == 'true' &&
      needs.initial-setup.outputs.skip_tests == 'false'

    uses: "dbt-labs/dbt-postgres/.github/workflows/integration-tests.yml@main"
    with:
      core_branch: "main"
      dbt_adapters_branch: "main"
```
currently tests against main for the adapter  

### Expected Behavior

it should test against the adapter version/branch being run through the workflow

### Steps To Reproduce

traceback:
when releasing https://github.com/dbt-labs/dbt-postgres/actions/runs/9024217690 initially we ran the workflow and ran into instances of failures for tests that didn't exist on the 1.8.latest branch but did on the main branch.
